# Generated by Django 5.2.3 on 2025-06-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_numbers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='legs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
