# Generated by Django 5.2.3 on 2025-06-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_flight_numbers_alter_flight_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='flight',
            name='legs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
